### ISSUE TITLE
pip install phe fails

### ISSUE THREAD

**Issue by muelli** [NICTA/python-paillier#1]
```
$ pip install phe
Downloading/unpacking phe
  Using download cache from ~/.pip_download_cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fp%2Fphe%2Fphe-1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-m65X6X/phe/setup.py) egg_info for package phe
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-m65X6X/phe/setup.py", line 31, in <module>
        long_description=open("README.md").read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-m65X6X/phe/setup.py", line 31, in <module>

    long_description=open("README.md").read(),

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-m65X6X/phe
➜ ~>
```

**Comment by hardbyte** [comment]
Confirmed for Python2. Not an issue in Python3

**Comment by felixlawrence** [comment]
Have you backported it to Python 2? It was written for Python 3 originally - not sure it's just the install that would fail on Python 2...

**Comment by hardbyte** [comment]
Good point @felixlawrence, there would be many more issues! Sorry @muelli this package currently requires Python 3.3+

**Comment by muelli** [comment]
Well. I don't care all too much.  I am happy to use python3. I just didn't know.

I guess you want to somehow avoid to confuse your users who do a "pip install" on their regular Ubuntu installation. Maybe issue a prominent warning when setup.py is executed with python2. Or check what other python3 projects are doing.

The list of incompatibilities isn't overly long, though.  It's too much for me to backport Python3 artifacts though.
