### ISSUE TITLE
invalid syntax error on  MAC

### ISSUE THREAD

**Issue by rajeswar18** [NICTA/python-paillier#27]
When i try to install phe on OSX i get the following error
File "build/bdist.macosx-10.6-x86_64/egg/phe/command_line.py", line 117
    print(serialised, file=output)
                          ^
SyntaxError: invalid syntax

**Comment by hardbyte** [comment]
Hi @rajeswar18 this package won't work with Python 2. 

Please reopen if you're using Python 3 and observed this issue.
