### ISSUE TITLE
Test using different base for EncodedNumber 

### ISSUE THREAD

**Issue by hardbyte** [NICTA/python-paillier#3]
All the current unit tests use BASE=16. Add tests with BASE=2, and documentation/example of using different base.

**Comment by felixlawrence** [comment]
(Tell the users to) Be careful when designing protocols with BASE=2 - if you don't require specific a specific value for the unencrypted exponents after an operation then you're potentially leaking a lot of information about what happened.

On a more mundane note, I can't remember if there were machine precision/rounding issues with non-power-of-two bases...

**Comment by hardbyte** [comment]
Thanks @felixlawrence, I've noted that loudly in the docs. Do you feel like reviewing the [pull request](https://github.com/NICTA/python-paillier/pull/4)?
